Models/Saving.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SmartBudget.Models
{
    public class Saving
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)"),]
        [Range(0, double.MaxValue, ErrorMessage = "Please provide positive number.")]
        public decimal AmountGoal { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)"),]
        [Range(0, double.MaxValue, ErrorMessage = "Please provide positive number.")]
        public decimal CurrentAmount { get; set; }

        //------------------------ Many savings relationship------------------------
        public int UserId { get; set; } // one user
        public virtual User User { get; set; }

        //------------------------ Many savings relationship------------------------
        
        //------------------------ One saving relationship------------------------
        public virtual ICollection<SavingLog> SavingLog { get; set; } //many saving logs

        //------------------------ One saving relationship------------------------

        [Required]
        [Display(Name = "Date of creation")]
        [DataType(DataType.DateTime)]
        public DateTime CreatedAt { get; set; }

        [Required]
        public bool IsCompleted { get; set; } = false;
    }
}

Controllers/SavingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartBudget.Data;
using SmartBudget.Models;
using SmartBudget.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SmartBudget.Controllers
{
    public class SavingController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SavingController(ApplicationDbContext db)
        {
            _db = db;
        }

        private User GetUserByUsername()
        {
            var username = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            User user = _db.Users.Where(u => u.Username == username).FirstOrDefault();
            return user;
        }

        [Authorize]
        public IActionResult Index()
        {
            User user = GetUserByUsername();
            IEnumerable<Saving> saving = _db.Savings.Include(s => s.User).Where(e => e.UserId == user.Id);
            return View(saving);
        }

        [Authorize]
        public IActionResult SavingCreate()
        {
            return View();
        }

        [Authorize]
        public IActionResult SavingDetails(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            User user = GetUserByUsername();
            SavingSavingLogs viewModel = new SavingSavingLogs();
            viewModel.Saving = _db.Savings.Include(s => s.User).Where(s => s.Id == id).First();
            if (viewModel.Saving == null)
            {
                return NotFound();
            }
            if (viewModel.Saving.UserId != user.Id)
            {
                return Forbid();
            }
            viewModel.SavingLogs = _db.SavingLogs.Include(s => s.Saving).Where(s => s.SavingId == viewModel.Saving.Id);
            return View(viewModel);
        }

        [Authorize]
        public IActionResult SavingDelete(int? id)
        {
            if (!_db.Savings.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Saving saving = _db.Savings.Find(id);

            if (user.Id == saving.UserId)
            {
                return View(saving);
            }
            else
            {
                return Forbid();
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SavingCreate(Saving saving)
        {
            User user = GetUserByUsername();
            saving.UserId = user.Id;
            saving.CreatedAt = DateTime.Now;
            saving.CurrentAmount = Convert.ToDecimal(0);
            if (ModelState.IsValid)
            {
                _db.Savings.Add(saving);
                _db.SaveChanges();
                return Redirect("Index");
            }
            return View(saving);
        }


        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult WithdrawAmount(int? id, SavingLog savingLog)
        {
            if (savingLog.Amount <= 0)
            {
                TempData["SavingError"] = "Please provide positive amount";
            }
            if (String.IsNullOrEmpty(savingLog.Amount.ToString()))
            {
                TempData["SavingError"] = "Amount field is required";
            }
            if (id == null)
            {
                return BadRequest();
            }
            Saving saving = _db.Savings.Where(s => s.Id == id).First();
            if (saving == null)
            {
                return NotFound();
            }
            User user = GetUserByUsername();
            if (saving.UserId != user.Id)
            {
                return Forbid();
            }

            if (saving.CurrentAmount - savingLog.Amount < 0)
            {
                TempData["WithdrawError"] = "Operation cancelled. Insufficient balance.";
                return RedirectToAction("SavingDetails", new { id = saving.Id });
            }
            savingLog.SavingId = saving.Id;
            savingLog.Type = SavingLog.ExchangeType.Withdraw;
            savingLog.UpdatedAt = DateTime.Now;
            savingLog.Amount = Convert.ToDecimal(savingLog.Amount);
            if (ModelState.IsValid)
            {
                _db.SavingLogs.Add(savingLog);
                saving.CurrentAmount = saving.CurrentAmount - savingLog.Amount;
                _db.SaveChanges();
                return RedirectToAction("SavingDetails", new { id = saving.Id });
            }

            return RedirectToAction("SavingDetails", new { id = saving.Id });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAmount(int? id, SavingLog savingLog)
        {
            if (savingLog.Amount <= 0)
            {
                TempData["SavingError"] = "Please provide positive amount";
            }
            if (String.IsNullOrEmpty(savingLog.Amount.ToString()))
            {
                TempData["SavingError"] = "Amount field is required";
            }

            if (id == null)
            {
                return BadRequest();
            }
            Saving saving = _db.Savings.Where(s => s.Id == id).First();
            if (saving == null)
            {
                return NotFound();
            }
            User user = GetUserByUsername();
            if (saving.UserId != user.Id)
            {
                return Forbid();
            }

            savingLog.SavingId = saving.Id;
            savingLog.Type = SavingLog.ExchangeType.Save;
            savingLog.UpdatedAt = DateTime.Now;
            savingLog.Amount = Convert.ToDecimal(savingLog.Amount);
            if (ModelState.IsValid)
            {
                if (saving.CurrentAmount + savingLog.Amount > saving.AmountGoal)
                {
                    savingLog.Amount = saving.AmountGoal - saving.CurrentAmount;
                }

                saving.CurrentAmount = saving.CurrentAmount + savingLog.Amount;
                if (saving.CurrentAmount == saving.AmountGoal)
                {
                    saving.IsCompleted = true;
                }
                _db.SavingLogs.Add(savingLog);
                _db.SaveChanges();
                return RedirectToAction("SavingDetails", new { id = saving.Id });
            }
            return RedirectToAction("SavingDetails", new { id = saving.Id });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SavingDelete(int id)
        {
            if (!_db.Savings.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Saving saving = _db.Savings.Find(id);

            if (user.Id != saving.UserId)
            {
                return Forbid();
            }

            _db.Savings.Remove(saving);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Saving/Index.cshtml
@model IEnumerable<Saving>;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<style>
    tr:nth-child(even) {
        background-color: #d6ebfb;
    }

    a:link, a:visited {
        color: #17a2b8
    }
</style>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />
    <title>Savings</title>
</head>

<body>
    <div class="container h-100">
        <div class="row justify-content-between mt-5">
            <div class="col-4">
                <h2>Savings in progress</h2>
            </div>
            <div class="col-4">
                <a class="btn w-100 fw-bold" style="background-color: #d6ebfb;" asp-controller="Saving" asp-action="SavingCreate"> Create new saving</a> @*Connection between register and controler*@
            </div>
        </div>
        @if (Model.Count() > 0)
        {
            <table class="table">
                <tr>
                    <th class="text-info">Title</th>
                    <th class="text-info">Goal</th>
                    <th class="text-info">Current amount</th>
                    <th class="text-info">Progress</th>
                    <th class="text-info">Created at</th>
                    <th class="text-info">Options</th>
                </tr>
                @foreach (Saving item in Model.Where(i => i.IsCompleted == false).OrderByDescending(i => i.CreatedAt).ThenBy(i => i.Id))
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Title)</td>
                        <td>@Html.DisplayFor(modelItem => item.AmountGoal)</td>
                        <td>@Html.DisplayFor(modelItem => item.CurrentAmount)</td>
                        <td width="30%">
                            <span>@($"{Decimal.ToInt32(item.CurrentAmount / item.AmountGoal * 100)}%")</span>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-success" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: @($"{Decimal.ToInt32(item.CurrentAmount / item.AmountGoal * 100)}%"); "></div>
                            </div>
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
                        <td>
                            <a asp-action="SavingDetails" asp-route-id="@item.Id">Details</a>
                            <a asp-action="SavingDelete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No records</p>
        }
        <div class="row mt-5">
            <h2>Completed savings</h2>
        </div>

        <table class="table">
            <tr>
                <th class="text-info">Title</th>
                <th class="text-info">Amount</th>
                <th class="text-info">Created at</th>
                <th class="text-info">Options</th>
            </tr>
            @foreach (Saving item in Model.Where(i => i.IsCompleted == true).OrderByDescending(i => i.CreatedAt).ThenBy(i => i.Id))
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>@Html.DisplayFor(modelItem => item.AmountGoal)</td>
                    <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
                    <td>
                        <a asp-action="SavingDetails" asp-route-id="@item.Id">Details</a>
                        <a asp-action="SavingDelete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</body>

Views/Saving/SavingCreate.cshtml
@model SmartBudget.Models.Saving
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />
    <title>Savings</title>
</head>

<body>
    <div class="container h-100">
        <div class="row h-100 justify-content-center">
            <div class="col-6 align-self-center">
                <img class="img-fluid" src="~/images/saving.jpg" />
            </div>
            <div class="col-4 offset-1 align-self-center">
                <form method="post" asp-action="SavingCreate">
                    <div class="row">
                        <h3 class="text-info">Create new saving</h3>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Title</label>
                        <input type="text" asp-for="Title" class="form-control">
                        <span asp-validation-for="Title" class="text-info"></span>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Target amount</label>
                        <input type="text" asp-for="AmountGoal" class="form-control">
                        <span asp-validation-for="AmountGoal" class="text-info"></span>
                    </div>
                    <div class="d-grid gap-2 mt-2 d-md-flex justify-content-between mt-3">
                        <input type="submit" class="btn btn-info me-md-2 w-100" value="Create" />
                        <input type="submit" class="btn btn-info w-100" asp-controller="Saving" asp-action="Index" value="Back" /> @*Connection between create saving and index*@
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

Views/Saving/SavingDelete.cshtml
@model SmartBudget.Models.Saving
@{
    ViewData["Title"] = "SavingDelete";
}

<body>
    <div class="container h-100">
        <div class="row h-100 justify-content-start">
            <div class="col-4 mt-4">
                <form asp-action="SavingDelete" method="post" asp-route-id="@Model.Id">
                    <h2>Confirm deletion</h2>
                    <p>Are you sure you want to delete this item? Deleting <a class="text-info">@Model.Title</a> will also delete all history kept for this saving.</p>
                    <input class="btn btn-info" type="submit" value="Delete" />
                    <a class="btn btn-info" asp-controller="Saving" asp-action="Index">Back</a> @*Connection between income type delete and index*@
                </form>
            </div>
            <div class="col-1 mt-4 px-0">
                <img style="max-height: 150px;" src="~/images/DeleteConfirmSaving.png" />
            </div>
        </div>
    </div>
</body>

Views/Saving/SavingDetails.cshtml
@model SmartBudget.ViewModels.SavingSavingLogs;

@{
    ViewData["Title"] = "SavingDetails";
    var savingError = TempData["SavingError"] as string;

}

<style>
    tr:nth-child(even) {
        background-color: #d6ebfb;
    }
</style>

<body>
    <div class="container h-100">
        <div class="row justify-content-start mt-5">
            <h2>Saving details</h2>
            <div class="row justify-content-start">
                <div class="col-2">
                    <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                        <div class="card-header">Amount goal</div>
                        <div class="card-body">
                            <h4 class="card-title">@Model.Saving.AmountGoal</h4>
                        </div>
                    </div>
                </div>
                @if (!Model.Saving.IsCompleted)
                {
                    <div class="col-2">
                        <div class="card text-white bg-info mb-3" style="max-width: 20rem;">
                            <div class="card-header">Current amount</div>
                            <div class="card-body">
                                <h4 class="card-title">@Model.Saving.CurrentAmount</h4>
                            </div>
                        </div>
                    </div>
                    <div class="col-3 align-items-center ms-auto">
                        <form method="post">
                            <div class="row align-items-center">
                                <h6>Saving options</h6>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <input type="text" class="form-control" placeholder="Enter amount" asp-for="SavingLog.Amount" />
                                    @if (!String.IsNullOrEmpty(savingError))
                                    {
                                        <div class="alert alert-dismissible alert-info">
                                            <span>@savingError</span>
                                        </div>
                                    }
                                    <span asp-validation-for="@Model.SavingLog.Amount" class="text-info"></span>
                                </div>
                            </div>
                            <div class="d-grid gap-2 mt-2 d-md-flex justify-content-between">
                                <input type="submit" class="btn btn-success me-md-2 w-100" asp-action="AddAmount" asp-route-id="@Model.Saving.Id" value="Fund" />
                                <input type="submit" class="btn btn-danger w-100" asp-action="WithdrawAmount" asp-route-id="@Model.Saving.Id" value="Withdraw" />
                            </div>
                        </form>
                    </div>
                }
                else
                {
                    <div class="col-5">
                        <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                            <div class="card-header">Congratulations!</div>
                            <div class="card-body">
                                <h4 class="card-title">Goal completed.</h4>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="mt-4">
            <h2>History</h2>
            @if (Model.SavingLogs.Count() > 0)
            {
                <table class="table">
                    <tr>
                        <th>Amount</th>
                        <th>Type</th>
                        <th>Updated at</th>
                    </tr>
                    @foreach (SavingLog item in Model.SavingLogs.OrderByDescending(i => i.UpdatedAt).ThenBy(i => i.Id))
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                            @if (item.Type == 0)
                            {
                                <td><span class="badge bg-success w-50">Fund</span></td>
                            }
                            else
                            {
                                <td><span class="badge bg-danger w-50">Withdraw</span></td>
                            }
                            <td>@Html.DisplayFor(modelItem => item.UpdatedAt)</td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No records</p>
            }
        </div>
    </div>
</body>