Models/Reminder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmartBudget.Models
{
    public class Reminder
    {
        [Key]
        public int Id { get; set; }
        
        [Required]
        [MinLength(3,ErrorMessage = "Title should be at least three symbols")]
        public string Title { get; set; }

        public string Description { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime CreatedAt { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOfReminding { get; set; }
        
        public bool IsDisplayed { get; set; }

        //----------------------- Many reminders relationship-----------------------
        public int UserId { get; set; }
        public virtual User User { get; set; }
        //----------------------- Many reminders relationship-----------------------
    }
}

Controllers/ReminderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartBudget.Data;
using SmartBudget.Models;
using SmartBudget.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SmartBudget.Controllers
{
    public class ReminderController : Controller
    {

        private readonly ApplicationDbContext _db;

        public ReminderController(ApplicationDbContext db)
        {
            _db = db;
        }

        private User GetUserByUsername()
        {
            var username = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            User user = _db.Users.Where(u => u.Username == username).FirstOrDefault();
            return user;
        }

        [Authorize]
        public IActionResult Index()
        {
            User user = GetUserByUsername();
            IEnumerable<Reminder> reminders = _db.Reminders.Include(s => s.User).Where(r => r.UserId == user.Id);
            ReminderCategories reminderCategores = new ReminderCategories();
            reminderCategores.CurrentReminders = reminders.Where(r => r.DateOfReminding == DateTime.Today);
            reminderCategores.UpcomingReminders = reminders.Where(r => r.DateOfReminding > DateTime.Today);
            reminderCategores.PastReminders = reminders.Where(r => r.DateOfReminding < DateTime.Today);
            return View(reminderCategores);
        }

        [Authorize]
        public IActionResult ReminderCreate()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> ReminderEdit(int? id)
        {
            if (!_db.Reminders.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Reminder reminder = await _db.Reminders.FindAsync(id);

            if (user.Id == reminder.UserId)
            {
                return View(reminder);
            }
            else
            {
                return Forbid();
            }
        }

        [Authorize]
        public IActionResult ReminderDelete(int? id)
        {
            if (!_db.Reminders.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Reminder reminder = _db.Reminders.Find(id);

            if (user.Id == reminder.UserId)
            {
                return View(reminder);
            }
            else
            {
                return Forbid();
            }

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ReminderCreate(Reminder reminder)
        {
            User user = GetUserByUsername();

            reminder.CreatedAt = DateTime.Now;
            reminder.UserId = user.Id;
            reminder.IsDisplayed = false;

            if (ModelState.IsValid)
            {
                _db.Reminders.Add(reminder);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reminder);
        }

        [Authorize]
        [HttpPost, ActionName("ReminderEdit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReminderAction(int? id)
        {
            if (!_db.Reminders.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Reminder reminderToUpdate = await _db.Reminders.SingleOrDefaultAsync(s => s.Id == id);

            if (user.Id != reminderToUpdate.UserId)
            {
                return Forbid();
            }

            if (await TryUpdateModelAsync<Reminder>(reminderToUpdate, "", r => r.Title, r => r.Description, r => r.DateOfReminding))
            {
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            TempData["ReminderEditWarning"] = "Reminder is not changed. Please provide valid information.";
            return View(reminderToUpdate);

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReminderDelete(int id)
        {
            if (!_db.Reminders.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Reminder reminder = _db.Reminders.Find(id);

            if (user.Id != reminder.UserId)
            {
                return Forbid();
            }

            _db.Reminders.Remove(reminder);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ReminderDone(int? id)
        {
            if (!_db.Reminders.Any(obj => obj.Id == id))
            {
                return NotFound();
            }

            User user = GetUserByUsername();
            Reminder reminderToUpdate = await _db.Reminders.SingleOrDefaultAsync(s => s.Id == id);
           
            if (user.Id != reminderToUpdate.UserId)
            {
                return Forbid();
            }
            if (ModelState.IsValid)
            {
                reminderToUpdate.IsDisplayed = true;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Reminder/Index.cshtml
@model SmartBudget.ViewModels.ReminderCategories;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    tr:nth-child(even) {
        background-color: #f9ffbc;
    }

    a:active {
        background-color: #f9ffbc;
    }
</style>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />
    <title>Reminders</title>
</head>


<body>
    <div class="container">
        <div class="row justify-content-between pt-4">
            <div class="col-6 align-self-center">
                <h2>Current reminders</h2>
            </div>
            <div class="col-2 align-self-center">
                <a class="btn btn-warning" asp-controller="Reminder" asp-action="ReminderCreate"> Create new reminder</a> @*Connection between register and controler*@
            </div>
        </div>
        <div>
            @if (Model.CurrentReminders.Count() > 0)
            {
                <table class="table">
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Date of reminding</th>
                        <th>Options</th>
                    </tr>
                    @foreach (Reminder item in Model.CurrentReminders.OrderBy(i => i.DateOfReminding).ThenBy(i => i.CreatedAt))
                    {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td>@Html.DisplayFor(modelItem => item.DateOfReminding)</td>
                    @if (item.IsDisplayed)
                    {
                        <td>
                            <span class="badge rounded-pill bg-success">Completed</span>
                        </td>
                    }
                    else{
                    <td>
                        <form method="post">
                            <input type="submit" class="btn btn-primary btn-sm" asp-action="ReminderDone" asp-route-id="@item.Id" value="Complete" />
                        </form>
                    </td>
                    }
                </tr>
                    }
                </table>
            }
            else
            {
                <em>No records to display</em>
            }
        </div>
        <div class="col-6 align-self-center mt-5">
            <h2>Upcoming reminders</h2>
        </div>
        <div>
            @if (Model.UpcomingReminders.Count() > 0)
            {

                <table class="table">
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Date of reminding</th>
                        <th>Options</th>
                    </tr>
                    @foreach (Reminder item in Model.UpcomingReminders.Where(i => i.IsDisplayed == false).OrderBy(i => i.DateOfReminding).ThenBy(i => i.CreatedAt))
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Title)</td>
                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                            <td>@Html.DisplayFor(modelItem => item.DateOfReminding)</td>
                            <td>
                                <a style="color:gold" asp-action="ReminderEdit" asp-route-id="@item.Id">Edit</a>
                                <a style="color:gold" asp-action="ReminderDelete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>

                    }
                </table>
            }
            else
            {
                <em>No records to display</em>
            }
        </div>
        <div class="col-6 align-self-center mt-5">
            <h2>Past reminders</h2>
        </div>
        <div>
            @if (Model.PastReminders.Count() > 0)
            {
                <table class="table">
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Date of reminding</th>
                        <th>Options</th>
                    </tr>
                    @foreach (Reminder item in Model.PastReminders.Where(i => i.IsDisplayed == false).OrderBy(i => i.DateOfReminding).ThenBy(i => i.CreatedAt))
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Title)</td>
                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                            <td>@Html.DisplayFor(modelItem => item.DateOfReminding)</td>
                            <td>
                                <a style="color:gold" asp-action="ReminderEdit" asp-route-id="@item.Id">Edit</a>
                                <a style="color:gold" asp-action="ReminderDelete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>

                    }
                </table>
            }
            else
            {
                <em>No records to display</em>
            }
        </div>
    </div>
</body>

Views/Reminder/ReminderCreate.cshtml
@model SmartBudget.Models.Reminder
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Create";
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />
    <title>Reminders</title>
</head>

<body>
    <div class="container h-100">
        <div class="row h-100 justify-content-center">
            <div class="col-6 align-self-center">
                <img style="max-height:100%; max-width:100%" src="~/images/reminder.jpg" />
            </div>
            <div class="col-4 offset-1 align-self-center">
                <form method="post" asp-action="ReminderCreate">
                    <div class="row">
                        <h3 class="text-warning">Create new reminder</h3>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Title</label>
                        <input type="text" asp-for="Title" class="form-control">
                        <span asp-validation-for="Title" class="text-warning"></span>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Description</label>
                        <input type="text" asp-for="Description" class="form-control">
                        <span asp-validation-for="Description" class="text-warning"></span>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Date of reminding</label>
                        <input type="date" asp-for="DateOfReminding" class="form-control">
                        <span asp-validation-for="DateOfReminding" class="text-warning"></span>
                    </div>
                    <div class="d-grid gap-2 mt-2 d-md-flex justify-content-between mt-3">
                        <input type="submit" class="btn btn-warning me-md-2 w-100" value="Create" />
                        <input type="submit" class="btn btn-warning w-100" asp-controller="Reminder" asp-action="Index" value="Back" /> @*Connection between create reminder and index*@
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

Views/Reminder/ReminderDelete.cshtml
@model SmartBudget.Models.Reminder
@{
    ViewData["Title"] = "Delete";
}

<body>
    <div class="container h-100">
        <div class="row h-100 justify-content-start">
            <div class="col-4 mt-4">
                <form asp-action="ReminderDelete" method="post" asp-route-id="@Model.Id">
                    <h2>Confirm deletion</h2>
                    <p>Are you sure you want to <a class="text-warning">delete</a> this item?</p>
                    <input class="btn btn-warning" type="submit" value="Delete" />
                    <a class="btn btn-warning" asp-controller="Reminder" asp-action="Index">Back</a> @*Connection between delete and index*@
                </form>
            </div>
            <div class="col-1 mt-4 px-0">
                <img style="max-height: 150px;" src="~/images/DeleteConfirmReminder.png" />
            </div>
        </div>
    </div>
</body>

Views/Reminder/ReminderEdit.cshtml
@model SmartBudget.Models.Reminder
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Edit";
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-united.css" />
    <title>Reminders</title>
</head>

<body>
    <div class="container h-100">
        <div class="row h-100 justify-content-center">
            <div class="col-6 align-self-center">
                <img style="max-height:100%; max-width:100%" src="~/images/reminder.jpg" />
            </div>
            <div class="col-4 offset-1 align-self-center">
                <form method="post" asp-action="ReminderEdit">
                    <div class="row">
                        <h3 class="text-warning">Edit reminder</h3>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Title</label>
                        <input type="text" asp-for="Title" class="form-control">
                        <span asp-validation-for="Title" class="text-warning"></span>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Description</label>
                        <input type="text" asp-for="Description" class="form-control">
                        <span asp-validation-for="Description" class="text-warning"></span>
                    </div>
                    <div class="row">
                        <label class="col-form-label">Date of reminding</label>
                        <input type="date" asp-for="DateOfReminding" class="form-control">
                        <span asp-validation-for="DateOfReminding" class="text-warning"></span>
                    </div>
                    <div class="d-grid gap-2 mt-2 d-md-flex justify-content-between mt-3">
                        <input type="submit" class="btn btn-warning me-md-2 w-100" value="Edit" />
                        <input type="submit" class="btn btn-warning w-100" asp-controller="Reminder" asp-action="Index" value="Back" /> @*Connection between create reminder and index*@
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>